---
title: "Analiza danych ankietowych"
subtitle: "Raport 1"
author: "Klaudia Janicka 262268, Natalia Iwańska 262270"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
  \usepackage{booktabs}
  \usepackage{float}
  \renewcommand{\tablename}{Tab.}
  \renewcommand{\figurename}{Wykres}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=5) 

library("tidyverse")
library("vcd")
library("ggplot2")
library("knitr")
library("dplyr")
library("xtable")
library("kableExtra")
library("ggplot2")
library('likert')
```


# Część I

## Tablice liczności dla zmiennej A1

```{r}
personel <- read.csv2(file = "personel.csv", header=FALSE)
names(personel) <- c("D", "S", "A1", "A2", "W1", "W2", "P", "Wiek", "Wyk")
personel$A2[personel$A2 == '11'] = '1'
personel <- personel %>% mutate(across(D:Wyk, as.factor))
```


```{r}
tabA1 <- personel %>% count(A1) %>% mutate(prop=n/sum(n))

tabA1wyk1 <- personel %>% filter(Wyk=="1") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1wyk2 <- personel %>% filter(Wyk=="2") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1wyk3 <- personel %>% filter(Wyk=="3") %>% count(A1) %>% mutate(prop=n/sum(n))

tabA1Dz <- personel %>% filter(D=="Z") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1Dp <- personel %>% filter(D=="P") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1Ds <- personel %>% filter(D=="S") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1Do <- personel %>% filter(D=="O") %>% count(A1) %>% mutate(prop=n/sum(n))

tabA1Pk <- personel %>% filter(P=="K") %>% count(A1) %>% mutate(prop=n/sum(n))
tabA1Pm <- personel %>% filter(P=="M") %>% count(A1) %>% mutate(prop=n/sum(n))

```


```{r, results='asis'}
t <- kable(tabA1, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t1 <- kable(tabA1wyk1, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t2 <- kable(tabA1wyk2, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t3 <- kable(tabA1wyk3, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t4 <- kable(tabA1Dz, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t5 <- kable(tabA1Dp, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t6 <- kable(tabA1Ds, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t7 <- kable(tabA1Do, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t8 <- kable(tabA1Pk, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t9 <- kable(tabA1Pm, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)


cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t,
    "\\centering",
    "\\caption{Tablica liczności dla A1.}
      \\centering",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t1,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na Wyk=1.}
      \\centering",
    "\\end{minipage}
\\end{table}"
))

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t2,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na Wyk=2.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t3,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na Wyk=3.}
      \\centering",
    "\\end{minipage}
\\end{table}"
))  

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t4,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na D=Z.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t5,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na D=P.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t6,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na D=S.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t7,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na D=O.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t8,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na P=k.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t9,
    "\\centering",
    "\\caption{Tablica liczności dla A1 ze względu na P=m.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 
```


## Tablice liczności dla zmiennnej W1

```{r}
tabW1 <- personel %>% count(A1) %>% mutate(prop=n/sum(n))

tabW1wyk1 <- personel %>% filter(Wyk=="1") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1wyk2 <- personel %>% filter(Wyk=="2") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1wyk3 <- personel %>% filter(Wyk=="3") %>% count(A1) %>% mutate(prop=n/sum(n))

tabW1Dz <- personel %>% filter(D=="Z") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1Dp <- personel %>% filter(D=="P") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1Ds <- personel %>% filter(D=="S") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1Do <- personel %>% filter(D=="O") %>% count(A1) %>% mutate(prop=n/sum(n))

tabW1Pk <- personel %>% filter(P=="K") %>% count(A1) %>% mutate(prop=n/sum(n))
tabW1Pm <- personel %>% filter(P=="M") %>% count(A1) %>% mutate(prop=n/sum(n))
```


```{r, results='asis'}
tW <- kable(tabW1, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t1W <- kable(tabW1wyk1, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t2W <- kable(tabW1wyk2, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t3W <- kable(tabW1wyk3, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t4W <- kable(tabW1Dz, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t5W <- kable(tabW1Dp, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t6W <- kable(tabW1Ds, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t7W <- kable(tabW1Do, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t8W <- kable(tabW1Pk, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)

t9W <- kable(tabW1Pm, format = "latex", booktabs = TRUE) %>% 
    column_spec(1, border_left = TRUE, border_right = TRUE) %>%
    column_spec(3, border_left = TRUE, border_right = TRUE)


cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      tW,
    "\\centering",
    "\\caption{Tablica liczności dla W1.}
      \\centering",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t1W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na Wyk=1.}
      \\centering",
    "\\end{minipage}
\\end{table}"
))

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t2W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na Wyk=2.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t3W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na Wyk=3.}
      \\centering",
    "\\end{minipage}
\\end{table}"
))  

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t4W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na D=Z.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t5W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na D=P.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t6W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na D=S.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t7W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na D=O.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 

cat(c("\\begin{table}[H]
    \\begin{minipage}{.5\\linewidth}",
      t8W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na P=k.}",
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}",
      t9W,
    "\\centering",
    "\\caption{Tablica liczności dla W1 ze względu na P=m.}
      \\centering",
    "\\end{minipage}
\\end{table}"
)) 
```


## Tabele wielodzielcze

```{r, echo=TRUE, results='asis'}
kable(structable(W1~P, personel) %>% addmargins(),
      caption="Tabela wielodzielcza uzwlgędniająca zmienną W1 i P.") %>% 
      column_spec(1, border_left = TRUE) %>%
      column_spec(6, border_right = TRUE) %>%
      kable_styling(latex_options = "HOLD_position")
```

```{r, results='asis'}
kable(structable(W1~S, personel) %>% addmargins(), caption="Tabela wielodzielcza uzwlgędniająca zmienną W1 i S.") %>% 
    column_spec(1, border_left = TRUE) %>%
    column_spec(6, border_right = TRUE) %>%
    kable_styling(latex_options = "HOLD_position")
```

```{r, results='asis'}
kable(structable(A1~D, personel) %>% addmargins(), caption="Tabela wielodzielcza uzwlgędniająca zmienną A1 i D.") %>% 
    column_spec(1, border_left = TRUE) %>%
    column_spec(7, border_right = TRUE) %>%
    kable_styling(latex_options = "HOLD_position")
```


## Wykres słupkowy

```{r, echo=TRUE}
daneW1 <- personel %>% count(W1) %>% data.frame()

ggplot(daneW1, aes(x=W1, y=n)) + 
    geom_bar(stat = "identity", fill="hotpink") + 
    ggtitle("Wykres słupkowy dla W1")
```

```{r}
daneW2 <- personel %>% count(W2) %>% data.frame()

ggplot(daneW2, aes(x=W2, y=n)) + 
    geom_bar(stat = "identity", fill="hotpink") + 
    ggtitle("Wykres słupkowy dla W2")
```

Jakieś dwa zdanie tak jak mówiła, ale jej nie słuchałam, więc nie wiem.

## Wykres kołowy

```{r, echo=TRUE}
ggplot(daneW1, aes(x="", y=n, fill=W1)) + 
    geom_bar(stat="identity", width=1) + 
    coord_polar("y", start=0) +
    theme_void() +
    scale_fill_brewer(palette="RdPu") + 
    ggtitle("Wykres kołowy dla W1")
```

```{r}
 ggplot(daneW2, aes(x="", y=n, fill=W2)) + 
    geom_bar(stat="identity", width=1) + 
    coord_polar("y", start=0) +
    scale_fill_brewer(palette="RdPu") + 
    theme_void() +
    ggtitle("Wykres kołowy dla W2")
```

## Wykresy mozaikowe

```{r, echo=TRUE}
mosaic(~D+A1, personel)
```
```{r}
mosaic(~D+W1, personel)
```
```{r}
mosaic(~S+P, personel)
```
```{r}
mosaic(~P+W1, personel)
```

# Część II

## Funkcja losująca ze zwracaniem i bez

```{r, echo=TRUE}
f <- function(x='bez'){
  if (x=='zwracanie'){
    s <- sample(1:nrow(mtcars),3,replace=TRUE)
  } else{
    s <- sample(1:nrow(mtcars),3)
  }
  mtcars[s, ]
}

f('zwracanie')
```
## Funkcja likert

```{r, echo=TRUE}
df <- data.frame(personel$A1,personel$A2)
colnames(df) <- c('Atmosfera przed wyjazdem', 'Atmosfera po wyjeździe')
likt_atmo <- likert(df)
summary(likt_atmo)
likert.bar.plot(likt_atmo) + scale_fill_discrete(labels=c('Zdecydowanie się nie zgadzam', 'Nie zgadzam się','Trudno powiedzieć','Zgadzam się','Zdecydowanie się zgadzam')) + guides(fill=guide_legend(nrow=2,byrow=TRUE,title='Odpowiedź')) + theme(axis.text.y=element_text(angle=45,hjust=1))

plot(likt_atmo,type='heat') + scale_y_discrete(
    labels = c('Zdecydowanie się nie zgadzam', 'Nie zgadzam się','Trudno powiedzieć','Zgadzam się','Zdecydowanie się zgadzam',
               'Średnia (odch.stand.)')) + theme(axis.text.x=element_text(angle=90,hjust=1),axis.text.y=element_text(angle=45,hjust=1)) + guides(fill=guide_legend(title='Odpowiedź'))

plot(likt_atmo,type='density') 
```

## Podgrupa ze względu na dział

```{r, echo=FALSE}
likt_atmo_gr_D <- likert(data.frame(personel$A1,personel$A2),grouping=personel$D)
summary(likt_atmo_gr_D)
likert.bar.plot(likt_atmo_gr_D) + scale_fill_discrete(labels=c('Zdecydowanie się nie zgadzam', 'Nie zgadzam się','Trudno powiedzieć','Zgadzam się','Zdecydowanie się zgadzam')) + guides(fill=guide_legend(nrow=2,byrow=TRUE,title='Odpowiedź')) + theme(axis.text.y=element_text(angle=45,hjust=1))

plot(likt_atmo_gr_D,type='density')
```

## Podgrupa ze względu na płeć

```{r, echo=FALSE}
likt_atmo_gr_P <- likert(data.frame(personel$A1,personel$A2),grouping=personel$P)
summary(likt_atmo_gr_P)

likert.bar.plot(likt_atmo_gr_P) + scale_fill_discrete(labels=c('Zdecydowanie się nie zgadzam', 'Nie zgadzam się','Trudno powiedzieć','Zgadzam się','Zdecydowanie się zgadzam')) + guides(fill=guide_legend(nrow=2,byrow=TRUE,title='Odpowiedź')) + theme(axis.text.y=element_text(angle=45,hjust=1))

plot(likt_atmo_gr_P,type='density')
```
