---
title: "Raport 2"
author: "Natalia Iwańska 262270, Klaudia Janicka 262268"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=4.5) 
pdf.options(encoding = 'CP1250')
```

```{r, include=FALSE, echo=FALSE}
library("tidyverse")
library("vcd")
library("ggplot2")
library("knitr")
library("dplyr")
library("xtable")
library("kableExtra")
library("ggplot2")
library('likert')
library("binom")
```

```{r, include=FALSE, echo=FALSE}
personel <- read.csv2('personel.csv',header=FALSE)
names(personel) <- c('D','S','A1','A2','W1','W2','P','Wiek','Wyk')
personel$A2[personel$A2 == '11'] = '1'
personel <- personel %>% mutate(across(D:Wyk,as.factor))
```

# Zadanie 2

```{r, echo=FALSE}
t2 <- structable(P~S,personel) %>% addmargins()
t1 <- ftable(personel$P,personel$S)
test2 <- fisher.test(t1)
```

```{=latex}
\begin{table}[ht]
\centering
\begin{tabular}{|c|c|c|c|}
  \hline
 & K & M \\ 
  \hline
0 & 63.00 & 110.00 \\ 
\hline
  1 & 8.00 & 19.00 \\ 
   \hline
\end{tabular}
\end{table}
```

```{r}
test2$p.value
```




**Wnioski**


# Zadanie 3

```{r}
t3a <- ftable(personel,col.vars='S',row.vars='Wiek')
fisher.test(t3a)

t3b <- ftable(personel,col.vars='S',row.vars='Wyk')
fisher.test(t3b)
```

**Wnioski**


# zadanie 4

```{r}
t4a <- ftable(personel,col.vars='W1',row.vars='S')
fisher.test(t4a)

t4b <- ftable(personel,col.vars='W1',row.vars='Wyk')
fisher.test(t4b)

t4c <- ftable(personel,col.vars='W1',row.vars='P')
fisher.test(t4c)

t4d <- ftable(personel,col.vars='W1',row.vars='Wiek')
fisher.test(t4d, workspace = 271020)
```

**Wnioski**


